### PR TITLE
UUID post test fix

### PR DESCRIPTION
**Pull request by tylerelston**
Fixed tests to use UUIDs

### CODE REVIEW

**Review by debecerra — APPROVED** [review]
Still getting a few inbox tests fails, but if you haven't gotten to these yet I can handle it so you can focus on the likes API route fix.

**Comment by tylerelston** [comment]
> en to these yet I can handle it so you can focus on the likes API route fix.

I pushed another commit, not sure if that's what you're talking about though. All tests pass on my end now

**Comment by debecerra** [comment]
That's odd. Still getting these two failures. You're not getting these?

```
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
...................E...F............
======================================================================
ERROR: test_get_inbox (api.tests.test_inbox.InboxViewTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/diego/school/404/social-distribution/code/api/tests/test_inbox.py", line 188, in test_get_inbox
    resPost = res_data["items"][0]
IndexError: list index out of range

======================================================================
FAIL: test_post_local_post (api.tests.test_inbox.InboxViewTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/diego/school/404/social-distribution/code/api/tests/test_inbox.py", line 136, in test_post_local_post
    self.assertEqual(response.status_code, 200)
AssertionError: 500 != 200

----------------------------------------------------------------------
Ran 36 tests in 4.798s

FAILED (failures=1, errors=1)
Destroying test database for alias 'default'...
```

**Review by JawadHossain — APPROVED** [review]

**Comment by JawadHossain** [comment]
> That's odd. Still getting these two failures. You're not getting these?
> 
> ```
> Creating test database for alias 'default'...
> System check identified no issues (0 silenced).
> ...................E...F............
> ======================================================================
> ERROR: test_get_inbox (api.tests.test_inbox.InboxViewTests)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/diego/school/404/social-distribution/code/api/tests/test_inbox.py", line 188, in test_get_inbox
>     resPost = res_data["items"][0]
> IndexError: list index out of range
> 
> ======================================================================
> FAIL: test_post_local_post (api.tests.test_inbox.InboxViewTests)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/diego/school/404/social-distribution/code/api/tests/test_inbox.py", line 136, in test_post_local_post
>     self.assertEqual(response.status_code, 200)
> AssertionError: 500 != 200
> 
> ----------------------------------------------------------------------
> Ran 36 tests in 4.798s
> 
> FAILED (failures=1, errors=1)
> Destroying test database for alias 'default'...
> ```

Interesting, the tests pass on my machine too

**Comment by debecerra** [comment]
> > That's odd. Still getting these two failures. You're not getting these?
> > ```
> > Creating test database for alias 'default'...
> > System check identified no issues (0 silenced).
> > ...................E...F............
> > ======================================================================
> > ERROR: test_get_inbox (api.tests.test_inbox.InboxViewTests)
> > ----------------------------------------------------------------------
> > Traceback (most recent call last):
> >   File "/home/diego/school/404/social-distribution/code/api/tests/test_inbox.py", line 188, in test_get_inbox
> >     resPost = res_data["items"][0]
> > IndexError: list index out of range
> > 
> > ======================================================================
> > FAIL: test_post_local_post (api.tests.test_inbox.InboxViewTests)
> > ----------------------------------------------------------------------
> > Traceback (most recent call last):
> >   File "/home/diego/school/404/social-distribution/code/api/tests/test_inbox.py", line 136, in test_post_local_post
> >     self.assertEqual(response.status_code, 200)
> > AssertionError: 500 != 200
> > 
> > ----------------------------------------------------------------------
> > Ran 36 tests in 4.798s
> > 
> > FAILED (failures=1, errors=1)
> > Destroying test database for alias 'default'...
> > ```
> 
> Interesting, the tests pass on my machine too

Yep, no worries. Issue was on my end and was discussed in the discord.

**Pull request merged**
