### PR TITLE
Allow for single page view of remote posts

### PR DESCRIPTION
**Pull request by debecerra**
The issue was that the /app/comment-view route would only render LocalPosts created by LocalAuthors. This further had dependencies on other local-only functionality like Comments and the local-only stuff extended into some of the templates and tag templates. This PR addresses all that and allows us to display both types of posts by using a `/app/posts/local/id `path for local and `/app/posts/inbox/id` path for inbox posts.

### Summary
 - rename comment-post path to single-post path
 - allow single-post path to render both inbox posts and local posts
 - get comments for the post (either local/inbox) either as JSON so that same template files can render both types of posts. If local post then JSON is retrieved from the db. If inbox post then JSON is retrieved using API request
 - allow for liking on remote/local comments by sending the comment id as a hidden form input then making a POST to inbox
 - get comment likes by using API calls since we don't know if the post is local/remote
 - had to fix the comment likes API endpoint as it was only returning likes from local authors and not likes from remote/local authors
 
### Notes:
- One test fails but should be fixed once I merge in master with the reduce API calls PR.
 - I realized that POST /author/{author_id}/posts/{post_id}/comments is incorrect. It creates a comment by author_id, which is incorrect. author_id is the owner of the post, not the owner of the comment. Also, this should go in the front-end views.py since it redirects to the front-end.

### CODE REVIEW

**Comment by debecerra** [comment]
It's challenging to test the multi-server stuff but I think I got everything working. Let me know if you spot any issues

**Review by JawadHossain — APPROVED** [review]
Very good quality code. Thanks, Diego!
Works perfectly on clean DB. 

remote author post comments are not part of the pr, right? I should probably have that sent to the inbox route

**Review by olivier-vadiaval — APPROVED** [review]
Nice work! Works on clean db for me too 💯

**Comment by debecerra** [comment]
> Very good quality code. Thanks, Diego! Works perfectly on clean DB.
> 
> remote author post comments are not part of the pr, right? I should probably have that sent to the inbox route

Correct, that's one of the few things that I didn't do in this (since you said you were gonna work on it). This PR just handles fetching comments from the remote posts (not creating a comment). 

Comments should be sent to the inbox, yes.

**Pull request merged**
