### PR TITLE
Fix AJAX timing issue

### PR DESCRIPTION
**Pull request by olivier-vadiaval**
Prevent update to page content in callback in modal is open

The callback takes a bit of time to excute since it might take a bit of time before the ajax request returns. In that small gap of time, if the user opened a modal, the page would "freeze" when the callback finally updates the page content as a response is received.

### CODE REVIEW

**Comment by debecerra** [comment]
How long is this small gap of time? Are we talking less than a second?
If it freezes, how does one escape? Just refresh the page? Is this freeze the one that happens when the whole page goes a bit dark?

**Comment by olivier-vadiaval** [comment]
> How long is this small gap of time? Are we talking less than a second? If it freezes, how does one escape? Just refresh the page? Is this freeze the one that happens when the whole page goes a bit dark?

Yup, it's the one that goes dark. I noticed that the gap of time varies but I would say 1-2 seconds for me. If it freezes, the page must be refreshed.

**Comment by olivier-vadiaval** [comment]
It's like that.

image

**Comment by JawadHossain** [comment]
> It's like that.
> 
> image

hard to reproduce locally, as updates are very quick.

**Review by JawadHossain — APPROVED** [review]
Thanks!

**Review by debecerra — APPROVED** [review]
Sounds good, thanks for keeping on top of the fixes!

**Pull request merged**
